// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBub0kEPQM2DfLOLVDNwzXBWOfPa8JHA-M',
    appId: '1:221047757778:web:372d1381c6c0de1407460b',
    messagingSenderId: '221047757778',
    projectId: 'autocalltranslate',
    authDomain: 'autocalltranslate.firebaseapp.com',
    storageBucket: 'autocalltranslate.firebasestorage.app',
    measurementId: 'G-DX4J5NZHGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAnttyFc6SpKhvBPDfDD1fNo7_vPlAM6A',
    appId: '1:221047757778:android:a6e9919dd4466ecd07460b',
    messagingSenderId: '221047757778',
    projectId: 'autocalltranslate',
    storageBucket: 'autocalltranslate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXvsDJFVXUk5CKb9ZNYuBcV3M7l7VMlNs',
    appId: '1:221047757778:ios:8f240ac79638fee407460b',
    messagingSenderId: '221047757778',
    projectId: 'autocalltranslate',
    storageBucket: 'autocalltranslate.firebasestorage.app',
    iosBundleId: 'com.carbonari.vaani',
  );
}
